#:schema node_modules/wrangler/config-schema.json
name = "ghcr-badge"
main = "dist/index.js"
compatibility_date = "2025-02-26"
compatibility_flags = ["nodejs_compat"]
minify = true
logpush = false

[observability]
enabled = true
